/*CREATE TABLE IF NOT EXISTS alumno (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR,
    apellido VARCHAR,
    dni VARCHAR,
    email VARCHAR,
    pass VARCHAR
);*/

CREATE TABLE IF NOT EXISTS cuota (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dias_disponibles INTEGER, 
    dias_restantes INTEGER, 
    monto FLOAT, 
    fecha_vencimiento DATE, 
    descripcion_mes VARCHAR(30), 
    id_turno INTEGER REFERENCES  turnos(id)
)
